# Generated by Django 5.2.9 on 2025-12-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalculationResult',
            new_name='ToolCalculation',
        ),
    ]
